### ISSUE TITLE
Phantom district name

### ISSUE THREAD

**Issue by aubergine10** [Celisuis/ServiceRestrictions#14]
I don't have a 'High Heights' district

![image](https://user-images.githubusercontent.com/1386719/62765311-c9c51b00-ba87-11e9-9bad-3945b1283037.png)

Maybe the game auto-names the "rest of map" district? If that's the case it would be useful to detect that and call it "Areas with no district" (or whatever).

**Comment by Celisuis** [comment]
District[0] in the Array appears to belong to the rest of the Map. Tested in new game, no districts and slot 0 was taken. 

I'll add a check in for Slot 0 and rename it appropriately.
