### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by aubergine10** [Celisuis/ServiceRestrictions#18]
I assume I need to add some dll files somwwhere?

![image](https://user-images.githubusercontent.com/1386719/62805760-dfb6f800-bae8-11e9-937b-bc3f2c459861.png)

As it's not readily obvious what to do it might be worth adding some build instructions should anyone want to contrib. If you can jot down basic notes in this issue I'll send a PR with some formatted docs.

**Comment by Celisuis** [comment]
It needs a reference to Customize It Extended for the compatibility. This obviously only applies to people building from source

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aubergine10** [comment]
The source or the dll?

**Comment by Celisuis** [comment]
The dll file from the workshop. I'll also be uploading a compiled dll of Customize It Extended to its github page tomorrow which can be used if you're not subscribed on the workshop

**Comment by aubergine10** [comment]
I added reference path to the DLL file in the subscribed mod (workshop folder `C:\Program Files (x86)\Steam\steamapps\workshop\content\255710\1806759255\`) and that reduced down to three errors.

It's still complaining about the missing namespace:

![image](https://user-images.githubusercontent.com/1386719/62807927-9ec1e200-baee-11e9-94d6-e82bebf0b6eb.png)

The references are all showing as valid:

![image](https://user-images.githubusercontent.com/1386719/62807947-ad0ffe00-baee-11e9-8804-4538ca47e1dc.png)

**Comment by Celisuis** [comment]
I know why now. I haven't updated the workshop version today, I was supposed to do that but things got ahead of me. I'll do it now, give it a couple of minutes for steam to update it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Celisuis** [comment]
Just pushed the update. Also a recent dll file can now be found here: https://github.com/Celisuis/CustomizeItExtended/releases

**Comment by aubergine10** [comment]
Working now :) I'll add a .md detailing build process and send a PR in a bit.

**Comment by Celisuis** [comment]
No worries
