### ISSUE TITLE
Can I get contrib on the repo for easier PRs?

### ISSUE THREAD

**Issue by aubergine10** [Celisuis/ServiceRestrictions#19]
If so, make sure I can't directly write to master - everything I do should go through a PR.

**Comment by Celisuis** [comment]
Sent a collab link. If I've done it correctly, you should be able to push to the beta branch, and I'm required to review PRs for master.

However, I have no idea if I've done it properly, because I've never done it before.

**Comment by aubergine10** [comment]
Seems to work :)
