### ISSUE TITLE
Some way to invert restrictions?

### ISSUE THREAD

**Issue by aubergine10** [Celisuis/ServiceRestrictions#4]
Currently I can select what to include, and everything else will be excluded.

But what if I wanted "whole map, except this one district"?

Would be useful to have a way of inverting the meaning of the restrictions screen.

**Comment by Celisuis** [comment]
Invert Option has been added. Just need to connect it to the UI and test it.

**Comment by Celisuis** [comment]
Invert Option added in latest alpha release.
