### ISSUE TITLE
'This district only' is weird

### ISSUE THREAD

**Issue by aubergine10** [Celisuis/ServiceRestrictions#5]
The option for "this district only" seems weird. There are three issues:

1. It shows even if the building is not in a district which is confusing
2. It would be better to just show the name of the district (possibly in different text colour to make it stand out)
    * An example of setting text colour can be found in the [More Advanced Options Panel](https://steamcommunity.com/sharedfiles/filedetails/?id=1773106708) mod - will need decompiling with ILSpy as I can't find the source on github
3. Would be good to have it at top of list as it will be most commonly used

**Comment by aubergine10** [comment]
Also, does "this district only" mean that if I select the local district I can no longer choose other districts? I hope (assume) that is not the case.

**Comment by Celisuis** [comment]
Renamed and Moved in the latest update. Also changed the behaviour to allow coverage with other districts aswell.
